### PR TITLE
replace code block by quotes to restore functionality

### PR DESCRIPTION
**Pull request by nicerloop**

### CODE REVIEW

**Comment by KNOXDEV** [comment]
When built with quotes, the backup script errors when run on my computer. 
image

Likewise, when I replace those quotes with the code block, it runs fine and as intended.
I'm running with Windows 10 default, Powershell version 5.1.19041.1320

**Comment by nicerloop** [comment]
I observed just the opposite, that's why my initial PR used double quotes.
I checked using a clean vagrant box (https://app.vagrantup.com/gusztavvargadr/boxes/windows-10).

The backup-220211.ps1 script is produced by scoop-backup:
if (Get-Command -Name scoop -ErrorAction SilentlyContinue) {} else {iwr -useb get.scoop.sh | iex}
scoop install git
scoop bucket add knox https://github.com/KNOXDEV/knox-scoop
scoop bucket add main 
scoop bucket add nicerloop https://github.com/nicerloop/scoop-nicerloop
scoop install main/7zip
scoop install main/git
scoop install knox/scoop-backup
scoop install main/sudo
scoop install main/sudo
sudo powershell -Command {
scoop install --global nicerloop/dotnetcore-desktopruntime-3.1-np
scoop install --global nicerloop/dotnetcore-desktopruntime-5.0-np
}

and produces:

...
WARN  'sudo' (0.2020.01.26) is already installed.
Use 'scoop update sudo' to install a new version.
Cannot process the command because of a missing parameter. A command must follow -Command.
...

It works with double quotes instead of code block.

**Comment by KNOXDEV** [comment]
I see. Well, there must be an alternative syntax to both code blocks and double quotes that works on both of our setups. 

Can you try an alternative?

**Comment by KNOXDEV** [comment]
If #14 also resolves this issue for you, please close this when you get the chance. If not let me know.

Thanks again!

**Pull request closed without merging**
